-- 코드를 입력하세요
SELECT b.AUTHOR_ID
      ,a.AUTHOR_NAME
      ,b.CATEGORY
      ,SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK b
INNER JOIN AUTHOR a
        ON b.AUTHOR_ID = a.AUTHOR_ID
INNER JOIN BOOK_SALES bs
        ON b.BOOK_ID = bs.BOOK_ID
       AND bs.SALES_DATE LIKE '2022-01%'
GROUP BY b.AUTHOR_ID, b.CATEGORY
ORDER BY 1, 3 DESC