-- 코드를 입력하세요
WITH cte AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE < '2022-11-30' AND END_DATE >= '2022-11-01'
)

SELECT c.CAR_ID
      ,c.CAR_TYPE
      ,ROUND(c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30)  AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
       ON c.CAR_TYPE = p.CAR_TYPE
      AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_ID NOT IN (SELECT * FROM cte)
  AND c.CAR_TYPE IN ('세단', 'SUV')
  AND ROUND(c.DAILY_FEE * (1 - p.DISCOUNT_RATE / 100) * 30) BETWEEN 500000 AND 2000000
ORDER BY 3 DESC, 2, 1 DESC