-- 코드를 작성해주세요
WITH P AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
),
C AS (
    SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
),
F AS (
    SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
),
GRADE_TABLE AS (
    SELECT CASE WHEN ((d.SKILL_CODE & (SELECT CODE FROM P) > 0) AND d.SKILL_CODE & (SELECT CODE FROM F) > 0) THEN 'A'
                WHEN (d.SKILL_CODE & (SELECT CODE FROM C)) > 0 THEN 'B'
                WHEN (d.SKILL_CODE & (SELECT CODE FROM F)) > 0 THEN 'C'
            END AS GRADE
     , d.ID
     , d.EMAIL
    FROM DEVELOPERS d, P, F, C
)
SELECT GRADE, ID, EMAIL
FROM GRADE_TABLE
WHERE GRADE IS NOT NULL
ORDER BY 1, 2