-- 코드를 입력하세요
WITH cte AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
),
total AS (
    SELECT COUNT(*) FROM cte
)

SELECT YEAR(SALES_DATE) AS YEAR
      ,MONTH(SALES_DATE) AS MONTH
      ,COUNT(DISTINCT USER_ID) AS PUCHASED_USERS
      ,ROUND(COUNT(DISTINCT USER_ID) / (SELECT * FROM total), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT * FROM cte)
GROUP BY YEAR, MONTH
ORDER BY 1, 2