-- 코드를 작성해주세요
WITH RECURSIVE CTE AS (
    SELECT d.ID, d.PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA d
    WHERE d.PARENT_ID IS NULL
    UNION ALL
    SELECT d1.ID, d1.PARENT_ID, c.LEVEL + 1 AS LEVEL
    FROM ECOLI_DATA d1
    JOIN CTE c ON d1.PARENT_ID = c.ID
),
PARENT_TABLE AS (
    SELECT ID
         , LEVEL AS GENERATION
    FROM CTE c
    WHERE ID NOT IN (
        SELECT DISTINCT PARENT_ID
        FROM ECOLI_DATA
        WHERE PARENT_ID IS NOT NULL
    )
)
SELECT COUNT(*) AS COUNT
     , GENERATION
FROM PARENT_TABLE
GROUP BY GENERATION
ORDER BY 2
