-- 코드를 작성해주세요
SELECT CASE WHEN CEIL(MONTH(DIFFERENTIATION_DATE) / 3) = 1 THEN '1Q'
            WHEN CEIL(MONTH(DIFFERENTIATION_DATE) / 3) = 2 THEN '2Q'
            WHEN CEIL(MONTH(DIFFERENTIATION_DATE) / 3) = 3 THEN '3Q'
            ELSE '4Q'
        END AS QUARTER
      , COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY QUARTER
ORDER BY QUARTER