-- 코드를 입력하세요
SELECT p.PRODUCT_ID
      ,p.PRODUCT_NAME
      ,SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT p
INNER JOIN FOOD_ORDER o
        ON p.PRODUCT_ID = o.PRODUCT_ID
       AND o.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY PRODUCT_ID       
ORDER BY 3 DESC, 1