-- 코드를 작성해주세요
WITH YEAR_MAX AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
         , MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)
SELECT m.YEAR
     , m.SIZE - SIZE_OF_COLONY AS YEAR_DEV
     , e.ID
FROM ECOLI_DATA e
LEFT JOIN YEAR_MAX m
       ON YEAR(e.DIFFERENTIATION_DATE) = m.YEAR
ORDER BY 1, 2