-- 코드를 입력하세요
WITH truck AS (
    SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
),
cte AS (
    SELECT CAR_ID 
      ,CASE
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 7 AND 29
           THEN '7일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 BETWEEN 30 AND 89
           THEN '30일 이상'
           WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90
           THEN '90일 이상'
        END AS DURATION_TYPE
     ,HISTORY_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (SELECT CAR_ID FROM truck)
)

SELECT h.HISTORY_ID
      ,CASE
           WHEN DISCOUNT_RATE IS NULL
           THEN DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
           ELSE ROUND((DAILY_FEE * (1 - DISCOUNT_RATE / 100)) * (DATEDIFF(END_DATE, START_DATE) + 1))
       END AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h
INNER JOIN cte c
        ON h.HISTORY_ID = c.HISTORY_ID
INNER JOIN truck t
        ON t.CAR_ID = h.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
       ON p.DURATION_TYPE = c.DURATION_TYPE
      AND p.CAR_TYPE = '트럭'
ORDER BY 2 DESC, 1 DESC