-- 코드를 작성해주세요
SELECT SUM(SCORE) AS SCORE, he.EMP_NO, he.EMP_NAME, he.POSITION, he.EMAIL
FROM HR_GRADE hg
JOIN HR_EMPLOYEES he
  ON hg.EMP_NO = he.EMP_NO
GROUP BY(hg.EMP_NO)
ORDER BY SCORE DESC
LIMIT 1