-- 코드를 입력하세요
WITH cte AS (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT r.FOOD_TYPE
      ,r.REST_ID
      ,r.REST_NAME
      ,r.FAVORITES
FROM REST_INFO r
INNER JOIN cte c
        ON r.FOOD_TYPE = c.FOOD_TYPE
       AND r.FAVORITES = c.FAVORITES
ORDER BY FOOD_TYPE DESC