WITH RARE_ITEM AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)
SELECT i.ITEM_ID
     , i.ITEM_NAME
     , i.RARITY
FROM ITEM_INFO i
WHERE EXISTS (
    SELECT 1
    FROM ITEM_TREE t
    JOIN RARE_ITEM r ON t.PARENT_ITEM_ID = r.ITEM_ID
    WHERE t.ITEM_ID = i.ITEM_ID
)
ORDER BY i.ITEM_ID DESC;