-- 코드를 입력하세요

SELECT 
    CATEGORY, 
    MAX(PRICE) AS MAX_PRICE, 
    (
        SELECT PRODUCT_NAME 
        FROM FOOD_PRODUCT 
        WHERE CATEGORY = A.CATEGORY AND PRICE = MAX(A.PRICE)
    ) AS PRODUCT_NAME
FROM FOOD_PRODUCT A
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC;
