-- 코드를 입력하세요
SELECT DISTINCT(crcrh.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY crcrh
JOIN CAR_RENTAL_COMPANY_CAR crcr
  ON crcrh.CAR_ID = crcr.CAR_ID
 AND crcr.CAR_TYPE = '세단'
WHERE crcrh.START_DATE >= '2022-10-01'
ORDER BY crcrh.CAR_ID DESC