-- 코드를 작성해주세요
SELECT fi.ID, ni.FISH_NAME, fi.LENGTH
FROM FISH_INFO fi
JOIN FISH_NAME_INFO ni
  ON fi.FISH_TYPE = ni.FISH_TYPE
JOIN (
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) AS BIG_FISH 
  ON fi.FISH_TYPE = BIG_FISH.FISH_TYPE 
 AND fi.LENGTH = BIG_FISH.MAX_LENGTH
ORDER BY 1