-- 코드를 작성해주세요
SELECT d.ID
     , d.GENOTYPE
     , d0.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA d
LEFT JOIN ECOLI_DATA d0
       ON d.PARENT_ID = d0.ID
WHERE EXISTS (
    SELECT 1 
    FROM ECOLI_DATA d1
    WHERE d1.ID = d.PARENT_ID
      AND d.GENOTYPE & d1.GENOTYPE >= d1.GENOTYPE
)
ORDER BY 1