-- 코드를 입력하세요
WITH HOT_BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT("/home/grep/src/", u.BOARD_ID, "/", u.FILE_ID, u.FILE_NAME, u.FILE_EXT) AS 'FILE_PATH'
FROM USED_GOODS_FILE u
WHERE u.BOARD_ID = (
    SELECT BOARD_ID
    FROM HOT_BOARD
)
ORDER BY u.FILE_ID DESC

